Feat(Authentication): debugging authentication.
hugoMontevideo/easyPortfolioProject pull request #1
Opened 2023-11-17 09:38 UTC by hugoMontevideo

Adding properties to User(UserDetails)
branch feat/authentication #16

2023-11-17 13:43 UTC, Mekouar-Ayoub requested changes

2023-11-17 13:43 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/auth/SecurityController.java
> +            System.out.println("hello");
pas de console.log pour tester

2023-11-17 13:43 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/impl/JwtUserServiceImpl.java
> +        User user = new User();
mieux vaut faire un new avec les parametres

2023-11-17 13:43 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/user/UserService.java
> +    Authentication authenticate(String email, String password) throws Exception;
le probleme c'est que partout ailleur tu l'as appellé email

2023-11-17 13:43 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/connection/connection.component.ts
> +import { User } from '../user/user.interface';
dans un dossier models peut etre ?

2023-11-17 13:43 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/login/login-view.interface.ts
> +export interface LoginView{
je pense que tu peux trouver mieux comme nom

2023-11-17 13:43 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/services/portfolio.service.ts
> +        return this.http.get<any>(`${this.ENV_DEV}/${table}`, {responseType: "json"} );
une interface au lieu de any

2023-11-17 13:43 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/services/portfolio.service.ts
>          headers = headers.set("Authorization", "Bearer ");
utilise un interceptor

2023-11-17 13:43 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/services/portfolio.service.ts
> +            this.loginUser = JSON.parse(anything);
c'est quoi anything

2023-11-17 13:43 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/services/login.service.ts
> +    return this.httpClient.post<any>(`${this.ENV_BASE}/auth/authorize`, loginView, {responseType: "json"})
meme chose

2023-11-17 13:43 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/services/login.service.ts
> +        sessionStorage.setItem('currentUser', JSON.stringify(this.currentUser));
ça va pas te poser des soucis quand tu stringify ? quand tu voudra recuperer les valeurs ?

2023-11-17 21:10 UTC, hugoMontevideo commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/auth/SecurityController.java
> +            System.out.println("hello");
ok

2023-11-17 21:29 UTC, hugoMontevideo commented on api/src/main/java/com/simplon/easyportfolio/api/services/impl/JwtUserServiceImpl.java
> +        User user = new User();
ok

2023-11-17 21:39 UTC, hugoMontevideo commented on ngEasyPortfolio/src/app/connection/connection.component.ts
> +import { User } from '../user/user.interface';
J'avais un dossier models avec des classes, mais j'utilise les interfaces à leur place maintenant.

2023-11-17 21:45 UTC, hugoMontevideo commented on ngEasyPortfolio/src/app/login/login-view.interface.ts
> +export interface LoginView{
LoginMailPwd it's ok ?

2023-11-17 21:49 UTC, hugoMontevideo commented on ngEasyPortfolio/src/app/portfolio/services/portfolio.service.ts
> +        return this.http.get<any>(`${this.ENV_DEV}/${table}`, {responseType: "json"} );
ok.

2023-11-17 21:49 UTC, hugoMontevideo commented on ngEasyPortfolio/src/app/portfolio/services/portfolio.service.ts
>          headers = headers.set("Authorization", "Bearer ");
Done.

2023-11-20 09:09 UTC, hugoMontevideo commented on ngEasyPortfolio/src/app/portfolio/services/portfolio.service.ts
> +            this.loginUser = JSON.parse(anything);
Je passe par une variable intermédiaire pour pouvoir récupérer les données de la sessionStorage et hydrater le User. Si je les récupère directement, comme JSON.parse attend un string il ne parse pas parce qu'il considère que c'est un type any.

2023-11-20 10:23 UTC, hugoMontevideo commented on ngEasyPortfolio/src/app/services/login.service.ts
> +    return this.httpClient.post<any>(`${this.ENV_BASE}/auth/authorize`, loginView, {responseType: "json"})
Comme tu me l'as demandé, j'ai crée un service SessionStorageService qui gère la sessionStorage du navigateur.
login et token son enregistrés séparément pour éviter de stringify-parse.

2023-11-20 10:24 UTC, hugoMontevideo commented on ngEasyPortfolio/src/app/services/login.service.ts
> +        sessionStorage.setItem('currentUser', JSON.stringify(this.currentUser));
Résolu dans la question antérieure.

2023-11-20 11:25 UTC, hugoMontevideo commented on api/src/main/java/com/simplon/easyportfolio/api/services/user/UserService.java
> +    Authentication authenticate(String email, String password) throws Exception;
ok

2023-11-22 09:40 UTC, merged