Crud
hugoMontevideo/easyPortfolioProject pull request #2
Opened 2023-11-21 10:48 UTC by hugoMontevideo

portfoliobyId() dans l'api

2023-11-22 09:48 UTC, Mekouar-Ayoub requested changes

2023-11-22 09:48 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/login/login-user.interface.ts
>      conButton: string
connexionStatus en boolean

2023-11-22 09:48 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list/portfolio-list.component.ts
> +                login:"",
je preferais email ou username

2023-11-22 09:48 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/services/login.service.ts
> +    sessionStorage.clear();
evite le clear par ce que ça vide tout remove les un par un

2023-11-22 09:48 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/services/session-storage.service.ts
> +  public getLogin = (): string | any => {
ce serait mieux que getLogin ne renvoi que string

2023-11-22 20:58 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list/portfolio-list.component.ts
> +                login:"",
ok

2023-11-22 20:58 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/login/login-user.interface.ts
>      conButton: string
ok

2023-11-22 21:03 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/services/login.service.ts
> +    sessionStorage.clear();
ok

2023-11-22 21:06 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/services/session-storage.service.ts
> +  public getLogin = (): string | any => {
ok

2023-11-23 09:00 UTC, Mekouar-Ayoub requested changes

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/skills/SkillController.java
> +    PortfolioService portfolioService;
Mieux vaut avoir un service qui gère les deux

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/skills/SkillController.java
> +    PortfolioService portfolioService;
parce que la logique doit se situer dans service pas autre part

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioServiceRequestModel.java
>  package com.simplon.easyportfolio.api.services.portfolios;
Je comprend pas que tu ai deux classes services pour portfolio

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/skills/SkillService.java
> +    PortfolioRepository portfolioRepository;
Voilà ton skill service gere bien deux repository donc c'est le seul qui doit apparaitre dans ton controller

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/education/education.interface.ts
> +    id: number,
C'est un dto ou une interface de composant ?

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.scss
> +h5{
evite les selecteurs par type dans les composants, seulement dans app.component.css

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
> +  portfolioId: string|any;
mmmm any

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
> +      id:null,
initialise le plutot à -1

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
> +      this.loginUser.login = this.storageService.getLogin();
j'aurais prefere que ton service renvoi les deux données d'un coup

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
> +      if( this.loginUser.login != ""){
cette condition devrait peut etre etre gérée dans le service

2023-11-23 09:00 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/skill/skill.component.scss
> +p{
evite les selecteurs par type dans les composants

2023-11-23 10:20 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/portfolio/component/skill/skill.component.scss
> +p{
ok

2023-11-23 11:41 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
> +      this.loginUser.login = this.storageService.getLogin();
ok

2023-11-23 11:42 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
> +      if( this.loginUser.login != ""){
ok

2023-11-23 11:43 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
> +  portfolioId: string|any;
ok

2023-11-23 11:43 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
> +      id:null,
ok

2023-11-23 12:05 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.scss
> +h5{
ok

2023-11-23 13:21 UTC, hugomontes24 commented on ngEasyPortfolio/src/app/portfolio/component/education/education.interface.ts
> +    id: number,
une interface

2023-11-23 13:29 UTC, hugomontes24 commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioServiceRequestModel.java
>  package com.simplon.easyportfolio.api.services.portfolios;
j'avais une classe avec un id optionnal, mais je me suis rendu compte plus tard que j'avais besoin d'une classe avec un Long id et une autre sans id (creation de portfolio)

2023-11-23 13:29 UTC, hugomontes24 commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/skills/SkillController.java
> +    PortfolioService portfolioService;
ok

2023-11-23 13:30 UTC, hugomontes24 commented on api/src/main/java/com/simplon/easyportfolio/api/services/skills/SkillService.java
> +    PortfolioRepository portfolioRepository;
ok

2023-11-27 08:36 UTC, Mekouar-Ayoub requested changes

2023-11-27 08:36 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/auth/SecurityController.java
>                  dto.getPassword());
Je t'ai mis des commentaires directement sur le code pas dans la pull request

2023-11-28 09:19 UTC, Mekouar-Ayoub requested changes

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/portfolios/PortfolioController.java
>          if(portfolioService.findById(id) != null){
try catch plutot

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/projects/ProjectController.java
> +        PortfolioServiceModel portfolio = new PortfolioServiceModel(projectDTO.getPortfolioId());
je comprend pas pourquoi tu fais ça, il mappe pas automatiquement mapstruct ?

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioService.java
> +        ProjectRepositoryModel project = mapper.projectServiceRequestToRepositoryModel(projectServiceRequestModel);
tu arrive à mapper les listes à l'intérieur ?

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioService.java
> +        if (projectRepositoryModel.isEmpty()){
j'aime pas trop le isEmpty pourquoi tu teste pas null ?

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioService.java
> +            return new ProjectServiceResponseModel();
pourquoi tu retourne un objet vide ?

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioService.java
> +    public boolean deleteProject(Long id) {
try catch plutot que find puis delete

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioService.java
> +            return new EducationServiceResponseModel();
meme chose

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioService.java
> +        if(educationRepository.findById(id).isPresent()){
try catch

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioService.java
>      public void deleteExperience(Long id) {
try catch

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/projects/ProjectServiceRequestModel.java
> +public class ProjectServiceRequestModel {
tu as deux modeles de service ?

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/core/footer/footer.component.html
> +<p>footer works!</p>
magnifique

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/education/education.component.ts
> +  currentEducation: Education = {
plutot new Education comme nom

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/education/education.component.ts
> +    this.isEducationFormShowing = false;
ou est ce que tu fais la validation du formulaire ?

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/education/education.component.ts
> +    this.isEducationFormShowing = false;
et l'affichage des erreurs

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/experience/experience.component.ts
> +  @Input() experiences!:Experience[];
à quoi sert le !

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/experience/experience.component.ts
> +  currentExperience: Experience = {
newExperience ou addingExperienceObject

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.html
> +                    (click)="onEditClick($event)"
pourquoi tu lui passe l'event ?

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.html
> +                  (click)="onDeleteClick($event)"
ici aussi ?

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
> +  portfolioId:number = -1;
tu as porftolio id et un objet porfolio qui a un id, c'est quoi la différence entre les deux

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
>    table: string = 'portfolios';
à quoi il te sert ?

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/project.component.ts
> +  @Input() portfolioId!: number;
redondance du portfolioId

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/project.component.ts
> +  ngOnChanges(){
pourquoi dans le OnChanges ?

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/project.component.ts
> +    this.portfolioService.addProject('projects' , this.currentProject)
vu que mainteant tu as séparé tes composants mieux vaut que tu ai un service pour chacun de tes composants plutot qu'un service qui gère les 3 avec un string qui n'est meme pas une enum et donc prompt aux erreurs

2023-11-28 09:19 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/services/portfolio.service.ts
>          return this.http.get<any>(`${this.ENV_DEV}/${table}`, { responseType: "json"});
get any c'est pas bon

2023-11-29 17:08 UTC, hugoMontevideo commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/auth/SecurityController.java
>                  dto.getPassword());
ok.vu

2023-11-29 17:09 UTC, hugoMontevideo commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioService.java
> +        if (projectRepositoryModel.isEmpty()){
méthode à finaliser

2023-12-01 10:27 UTC, Mekouar-Ayoub requested changes

2023-12-01 10:27 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioService.java
> +    public String uploadPicture(MultipartFile file, String pictureName) throws IOError{
met la en private

2023-12-01 10:27 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/skills/SkillController.java
> +    @PostMapping("/{id}")
PutMapping

2023-12-01 10:27 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/skill/skill.component.ts
> + public onCloseForm = () => {
OnCloseModalForm plutot ?

2023-12-04 13:07 UTC, Mekouar-Ayoub approved these changes

2023-12-04 13:07 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/exceptions/AppHandlerException.java
> +
tu as suivi un tuto ?

2023-12-04 15:02 UTC, hugomontes24 commented
Salut,

oui


Hugo MACHADO
Developpeur    Web
06 66 26 19 76
________________________________
De : Mekouar Ayoub ***@***.***>
Envoyé : lundi 4 décembre 2023 14:07
À : hugoMontevideo/easyPortfolioProject ***@***.***>
Cc : MACHADO HUGO ***@***.***>; Comment ***@***.***>
Objet : Re: [hugoMontevideo/easyPortfolioProject] Crud (PR #2)


@Mekouar-Ayoub approved this pull request.

________________________________

In api/src/main/java/com/simplon/easyportfolio/api/exceptions/AppHandlerException.java<https://github.com/hugoMontevideo/easyPortfolioProject/pull/2#discussion_r1413845169>:

> @@ -0,0 +1,29 @@
+package com.simplon.easyportfolio.api.exceptions;
+


tu as suivi un tuto ?

—
Reply to this email directly, view it on GitHub<https://github.com/hugoMontevideo/easyPortfolioProject/pull/2#pullrequestreview-1762356920>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASUHOXAT4LJJULWPX53TURLYHXDKJAVCNFSM6AAAAAA7ULE2HSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONRSGM2TMOJSGA>.
You are receiving this because you commented.Message ID: ***@***.***>

2023-12-05 09:54 UTC, Mekouar-Ayoub requested changes

2023-12-05 09:54 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/services/portfolios/PortfolioService.java
> +            projectServiceRequestModel.setDate(null);
evite de set à null utilise les optionnal

2023-12-05 09:54 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/project.component.ts
> +                                            null,
si c'est un objet met le en {} si c'est un type primitif utilise une valeur par défaut

2023-12-07 11:38 UTC, Mekouar-Ayoub approved these changes

2023-12-07 11:38 UTC, Mekouar-Ayoub commented on api/src/main/java/com/simplon/easyportfolio/api/controllers/projects/ProjectController.java
> +        ProjectServiceRequestModel serviceModel = new ProjectServiceRequestModel(DTO.getTitle(), DTO.getPortfolioId());
un seul model pour ton service

2023-12-07 11:38 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/login/login.component.ts
> +                this.loginError="Mdp ou email invalides";
Mot de passe

2023-12-07 11:38 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/project.component.ts
> +  @Input() portfolioId!: number;
tu as pas modifié ça visiblement

2023-12-07 11:38 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/project.component.ts
> +    console.log("hello");
oublie pas de le changer met un TODO dessus

2023-12-07 11:38 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/services/education.service.ts
> +  saveEducation = ( table: string, newEducation: Education ): Observable<any> => {
le jour ou tu te trompe sur la table string tu vas passer 3 heures à chercher le probleme

2023-12-07 11:38 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/services/education.service.ts
> +    return this.http.put(`${this.ENV_DEV}/${table}/${newEducation.id}`, newEducation );
met la en dur ici la table

2023-12-08 10:29 UTC, Mekouar-Ayoub approved these changes

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/login/login.component.ts
> +                this.loginError="Mdp invalide";
je voulais te dire ecris Mot de passe pas Mdp

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/portfolio-list-item/portfolio-list-item.component.ts
> +                                      console.log(response);
pas de console log

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/document-project-model.ts
> +    constructor(
pas de constructeur pour les objets en Angular on utilise des interfaces

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/document-project-model.ts
> +     ){  }
en plus il est vide

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/project-model.ts
>  export class ProjectModel {
meme chose

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/project.component.html
> +        <div *ngFor="let doc of newProject.documents; let j = index">
tu utilise pas le j, si ?

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/project.component.ts
>                                                new ProjectModel(
{ 
id: data.id ...

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/component/project/project.component.ts
> +    console.log("hello", documentId);
pas de console.log(

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/services/project.service.ts
> +    console.log(newProject);
pas de console log

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/services/project.service.ts
> +    }else if ( newProject.date < defaultDate){
je sais pas si c'est une bonne idéee

2023-12-08 10:29 UTC, Mekouar-Ayoub commented on ngEasyPortfolio/src/app/portfolio/services/project.service.ts
> +    return this.http.delete(`${this.ENV_DEV}/${table}/${projectId}/documents/${documentId}` );
evite le ${table} ecris le en dur

2023-12-08 10:29 UTC, merged